float4 mainBlendSSS_fp( float2 uv : TEXCOORD0,
					    uniform sampler Scene : register(s0),
					    uniform sampler SSS : register(s1),
					    uniform float ThicknessScale,
					    uniform float Offset,
					    uniform float Luminance ) : COLOR
{
	float S = tex2D( SSS, uv ).x;
	float4 colour = tex2D( Scene, uv ) * (sqrt( ThicknessScale / S) + Offset) * Luminance;
	//float4 colour;
	//float factor = (sqrt( ThicknessScale / S) + Offset) * Luminance;
	//colour = factor;
	return colour;
}
